### ISSUE TITLE
Fatal error in Safari@iOS 9.32 and my own solution

### ISSUE THREAD

**Issue by JuniorTour** [PygmySlowLoris/vue-ripple-directive#6]
At first, thank you, Pygmy Slow Loris, thank you for your great work! 
This repo helped me saved a lot of work.

And then I want to report a fatal error in my practice of  applying this plugin to [my project - a SPA made by vue.js](http://juniortour.net:8080/me).

The error I met is, before I apply this plugin to my project, everything went well.
Once I import this plugin to my project, the page **will not render** on the Safari of my own iPhone se@iOS 9.3.2.
**Nothing showed in my window, only a blank page.**
And I also test this strange error on other devices: Chrome@58+ of my laptop run well, no error, no warning with ripple effect applied; Safari of iPhone 6p@iOS 10.3.2 also run well with ripple effect applied; the browser of an Android smart phone run perfect too; But Safari of iPhone 5s@iOS 9.3.2 met the same error as my own iPhone se@iOS 9.3.2. 

I also tried reset the setting of iPhone se@iOS 9.3.2, but my project still no render, so I exclude my iPhone as the error source.

So I think this plugin may have some problem with Safari@iOS 9.3.2.

And finally, after a self-check I **solved it** by change the src code - src/ripple.js directly. I only changed a line:
``` javascript
//line 5:
const props = {

//change to:
var props = {
```
After this source code change, the error in Safari of iPhone se@iOS 9.3.2 solved!

Could you explain the reason why you use `const` instead of `var` in ripple.js?

I don't  know the reason why it was solved, but I think you may need take the error and solution into consideration.

I hope this issue help us to improve this plugin! That is all, thank you again for your master-piece!

**Comment by hazzo** [comment]
Hi @JuniorTour, thanks for taking your time on submitting this issue. We are glad that this repo solved you some trouble.

The main reason that `const` was used instead of `var` was because we were using ES6 sytanx. But because we were not transpiling the code we decided to change everything to ES5 and it seems that we forget to change that variable declaration. 

So thank you very much for letting us know this issue. New version (`1.0.9`) will fix this error.
